### ISSUE TITLE
High frequency signal on the output when I change the frequency

### ISSUE THREAD

**Issue by T1j3ff** [RobTillaart/AD9833#10] opened 2023-12-13 19:46 UTC
Not sure If this is "By design" in the chip, 
Or if I have a cheap Chinese counterfeit chip, 
Or this is something possible improve in this library 

But I get some high frequency signal on the output when I change the frequency when I call the AD.setFrequency() function 
The transients last longer if I use the SW SPI , but is still present if using the HW SPI 

Using a Arduino Nano Every 
Using HW SPI  (AD9833 AD(9);) 
using square wave (AD.setWave(AD9833_SQUARE1))

This happen only when I change the frequency 
But is actually really painful if you plan to sweep frequency ! 

```
void set_freq (float f_khz){
  static float old_khz;

  digitalWrite(8,HIGH );
  if(f_khz != old_khz ){
     AD.setFrequency(f_khz*1000.0, 0);
     old_khz=f_khz;
  }
  digitalWrite(8, LOW);

}
```

The CH1 (yellow)  is the AD9833 output 
The CH2 (blue)  is the pin8 (use to trig the scope on my set_freq() function

![image](https://github.com/RobTillaart/AD9833/assets/11382177/aeb206c1-3471-4c72-95b5-c75eef752837)

**Comment by T1j3ff** [comment] 2023-12-13 19:51
Using SW SPI 
![image](https://github.com/RobTillaart/AD9833/assets/11382177/1b8ff20b-81c1-4f49-afc6-3983c5356744)

**Comment by RobTillaart** [comment] 2023-12-13 20:32
Thanks for reporting this issue,
Do not recall seeing such effects however I did not that much tests with hardware actually.
I need to check if I have time to find hardware to build a setup and test.

Have you tried if another board e.g. esp32 or uno give the same problem (to determine if it is in the library).

**Comment by RobTillaart** [comment] 2023-12-13 20:48
Had a look at the code and low level a new frequency is written in 2 calls (2x 14 bits). I need to dive in the datasheet what it says about it. 

It might be possible (hypothesis) that two transactions creates an extra "in between" frequency. Although I cannot see yet why that would be such a high frequency. 

To be continued tomorrow if time permits.

**Comment by T1j3ff** [comment] 2023-12-13 21:15
I will try tomorrow with an ESP32 
But I found a dirty work-around for now ,,, I've and a AND gate between signals (and invert pin8 signal in code)

**Comment by RobTillaart** [comment] 2023-12-14 03:01
Your work around means you silence the output while switching frequency. Can you hear / notice that in the transition when doing a sweep?

**Comment by RobTillaart** [comment] 2023-12-14 11:45
@KarenColumbo

Have you ever encountered such a "frequency glitch"

**Comment by RobTillaart** [comment] 2023-12-14 12:09
@T1j3ff 
Do you get the "frequency glitch" also with sine or triangle?

**Comment by RobTillaart** [comment] 2023-12-14 13:49
Scrutenized the **writeFreqRegister()** function

```cpp
void AD9833::writeFreqRegister(uint8_t reg, uint32_t freq)
{
  uint16_t data = 0;
  if (reg > 1) return;
  if (reg == 0) data = 0x4000;  //  bit 15 and 14    01
  if (reg == 1) data = 0x8000;  //  bit 15 and 14    10

  //  28 bits in two sets of 14
  data |= (freq & 0x3FFF);  //  least significant 14 bits
  writeData(data);

  data &= 0xC000;           //  remove freq data LSB
  data |= (freq >> 14);     //  most significant  14 bits
  writeData(data);
}
```

#### Analysis

1. if the parameter **freq** is larger than 28 bit (268.435.456) there will be an error in the second **writeData()** call
2. if **hardwareReset()** has been called before **writeFreqRegister()** the control register might not be set correctly, in concreto the B28 bit, which is correctly set in the **reset()** call.

Don't know if either is causing the "frequency glitch" but both need to be fixed asap.

@T1j3ff 

Q1: Do you call the **hardwareReset()** in your program?

**Comment by RobTillaart** [comment] 2023-12-14 14:06
>  It might be possible (hypothesis) that two transactions creates an extra "in between" frequency. Although I cannot see yet why that would be such a high frequency.

Not so

**Page 14 datasheet**
_Two write operations are required to load a complete word into either of the frequency registers. B28 = 1 allows a complete word to be loaded into a frequency register in two consecutive writes. The first write contains the 14 LSBs of the frequency word, and the next write contains the 14 MSBs. The first two bits of each 16-bit word define the frequency register to which the word is loaded, and should therefore be the same for both of the consecutive writes. See Table 8 for the appropriate addresses. The write to the frequency register occurs after both words have been loaded; therefore, the register never holds an intermediate value._

**Comment by RobTillaart** [comment] 2023-12-14 14:53
@T1j3ff 
Created a develop branch with improved setFrequencyRegister() fixing the above bugs.

You might give it a try to see if it makes a difference,
Code will be released somewhere coming days (might be some more to add)

**Comment by T1j3ff** [comment] 2023-12-14 15:50
I wont be using this chip anymore for my project , so don't rush it just for me 

AD9833_SQUARE1
AD9833_SQUARE2
AD9833_TRIANGLE
AD9833_SINE
All 4 Suffer from "the glitch" 

I'm not using hardwareReset() anywere 

I cant measure it adequately, but the High frequency signal seem to be way higher when going from 5.0-5.1khz thant 6.0 to 6.1 khz ... This seems to corroborate the 14 bit lsb-msb theory

**Comment by T1j3ff** [comment] 2023-12-14 16:12
I'm not super knowledgeable on how to make a fork and so , on github , So I'll let you make forks and manage code

The "__SPI_CLASS__" mod you just did on 0.2.1 broke support for My nano every 

```
In file included from D:\code\code_v004\code_v004.ino:12:0:
C:\Users\moi\Documents\Arduino\libraries\AD9833/AD9833.h:43:31: error: '__SPI_CLASS__' has not been declared
   AD9833(uint8_t slaveSelect, __SPI_CLASS__ * mySPI = &SPI);
                               ^~~~~~~~~~~~~
C:\Users\moi\Documents\Arduino\libraries\AD9833/AD9833.h:92:3: error: '__SPI_CLASS__' does not name a type
   __SPI_CLASS__ * _mySPI;
   ^~~~~~~~~~~~~
C:\Users\moi\Documents\Arduino\libraries\AD9833/AD9833.h:43:55: error: could not convert '& SPI' from 'SPIClassMegaAVR*' to 'int*'
   AD9833(uint8_t slaveSelect, __SPI_CLASS__ * mySPI = &SPI);
                                                       ^~~~
```

I've replace this block
```
#if defined(__SPI_CLASS__)
  #if defined(ARDUINO_ARCH_RP2040)
  #define __SPI_CLASS__   SPIClassRP2040
  #else
  #define __SPI_CLASS__   SPIClass
  #endif
#endif
```

 with 
```  #define __SPI_CLASS__   SPIClass```
Just as a dirty work-around 

And after ,,, the glitch is still present :(

**Comment by RobTillaart** [comment] 2023-12-14 16:23
> The __SPI_CLASS__ bug 

Is fixed, I forgot an !  == invert the existence of the define
"If it is NOT defined, the library should define it"
Your workaround is super OK for testing.
The glitch still being there at least shows it is not caused by the two bugs I found in the review of setFrequencyRegister,
so your test is valuable.

-----

> I wont be using this chip anymore for my project , so don't rush it just for me

No problem, 
I "rush" to get bugs out of the library only if time permits.

> ... High frequency signal seem to be way higher ...

If I look at the scope signal I estimate that "the glitch" is at least 10x the frequency, so at least 50 KHz (?)
Given that you only go from 5.0 -> 5.1 kHz the intermediate values are expected to be in between as the MSB will only change slightly.


>  All 4 Suffer from "the glitch"

Thanks for testing, appreciated

> I'm not using hardwareReset() anywere

That is good in the sense that the B28 control bit should be set during the whole process.

----

I can only think of one possible cause. When setting the frequency bits LSB and MSB there are two calls to **writeData()**
These are separate transactions.
I will change the develop branch so it will be done in one transaction.
Do you have time to give it a try?
(I will let you now when the develop branch is patched)

**Comment by T1j3ff** [comment] 2023-12-14 16:32
Yes, I do have time to test whatever you want 

But My esp32 seems to be "fried" so I can't test this one 


I've seen other counterfeit chip before ... 
This would not surprise me , accounting the official chip alone worth more than the bord I purchase 

Mine is this one:
https://www.amazon.ca/dp/B0CJ9WHK4R?psc=1&ref=ppx_yo2ov_dt_b_product_details
it is writen "WCMCU-9833" on the back ... google found no result for this one 
But give me result for a similar board "CJMCU-9833" ... 
So it seems I have a copy of an other chinese board 

It may worth a try for sombody to reproduce the "glitch" test on a official chip.

**Comment by RobTillaart** [comment] 2023-12-14 16:52
I've patched the develop branch, build is running.
Did performance test (which can be done without the chip, still have to search for it) on UNO.
getFrequency got slightly faster from 36 to 24 us.

to do:  performance test on an ESP32

**Comment by T1j3ff** [comment] 2023-12-14 16:54
I've drill it down when the glich happen to here : 
```
  digitalWrite(8,LOW ); 
  writeData(MSB);
  digitalWrite(8, HIGH);
```

![image](https://github.com/RobTillaart/AD9833/assets/11382177/c20ff84b-f648-4fd7-9bb7-ad10bfeeafa3)

**Comment by RobTillaart** [comment] 2023-12-14 17:02
So shifting in 16 bits let it "crash"

The new version with one transaction for LSB and MSB is ready.
I'm eager to see the scope images,
(first I have dinner and dishes)

**Comment by T1j3ff** [comment] 2023-12-14 17:55
Testing last Code: 
On SW SPI   going from 5.00khz to 6.000khz on nano every 

Drilling it down to Trigger on :
```
    digitalWrite(8,LOW );
    
    for (uint16_t mask = 0x8000; mask; mask >>= 1)
    {
      digitalWrite(dao, (MSB & mask) !=0 ? HIGH : LOW);
      digitalWrite(clk, LOW);
      digitalWrite(clk, HIGH);
    }
    digitalWrite(dao, LOW);

    digitalWrite(8, HIGH);

```

![image](https://github.com/RobTillaart/AD9833/assets/11382177/e63430f1-9c9e-4e82-bcbe-0cc6ef10a8ec)








On HW SPI ( AD9833 AD(9) )  going from 5.00khz to 6.000khz on nano every 

Drilling it down to trigger here : 
```
    digitalWrite(8,LOW );
    _mySPI->transfer16(MSB);
    digitalWrite(8, HIGH);

```
 
![image](https://github.com/RobTillaart/AD9833/assets/11382177/3ca6f0df-c806-43c6-9ede-85fdd64f01e4)

Glitch last about the same time as the transfer16() function ,,, but i've just noticed it actually start before,  


If I Trigger it here instead 
```
    digitalWrite(8,LOW );
    _mySPI->transfer16(LSB);
    digitalWrite(8, HIGH);
```
We can see it start half way "digesting" the LSB 
![image](https://github.com/RobTillaart/AD9833/assets/11382177/44241670-8caa-49fd-b9e4-259052ff6911)

**Comment by RobTillaart** [comment] 2023-12-14 18:09
Thank you very much for these tests, Gives me something to think about, what kind of scenario would cause this.

The only scenario I can come up with at the moment is:
- the data is shifted into the LSB and MSB register.
- during the actual shift-in the bit-pattern in the register changes and it is made actual with every new bit
- the 9833 tries to output the value for the new bit pattern "real time"

So somehow the update of the output should be postponed until update is done.
That is something to search for in the datasheet.

**Comment by T1j3ff** [comment] 2023-12-14 19:41
I also had an LCD on the SPI line ,,, I've remove it
 no improvement 

I've substitute the "nano every"   for a "plain nano" clone 
 no improvement 

most basic code I can use to reproduce issue: 

Button to grd on pin2 



```

#include <Arduino.h>
#include <SPI.h>
#include "AD9833.h"

AD9833 AD(9);  //  SW SPI over the HW SPI pins
//AD9833 AD(9, 11, 13);  // HW SPI pins

void setup(){
  AD.begin();
  AD.setWave(AD9833_SQUARE1);
  pinMode(8, OUTPUT);
  pinMode(2, INPUT_PULLUP);
  AD.setFrequencyChannel(0);
}

void set_freq (float hz){
  static float old_hz;
  if(hz != old_hz ){
     AD.setFrequency(hz , 0); 
     old_hz=hz;
  }
}

void loop(){
  float fNow;
  while(1) {
    if (digitalRead(2)) fNow = 5000;
    else  fNow = 6000;
    set_freq(fNow);
  }
}

```

**Comment by RobTillaart** [comment] 2023-12-15 13:03
@T1j3ff 

Your constructor is **AD9833 AD(9);**
So slaveSelectPin = 9, this is (should be) connected to the FSYNC pin of the chip?

**Comment by T1j3ff** [comment] 2023-12-15 17:04
So slaveSelectPin = 9, this is (should be) connected to the FSYNC

--> Yes Pin9 is connected to CS of the chip (FSYNC) ,Just tried removing it , com to the chip stopped working. Ive tried pin 10 instead , no improvement

**Comment by T1j3ff** [comment] 2023-12-15 18:37
Well ,,, we are not chasing something impossible ,And My chip is not defective 
![image](https://github.com/RobTillaart/AD9833/assets/11382177/258ada99-eeb9-44a6-8d2a-08b6a22560a1)

This glitch does not happen if I use this Library
https://github.com/MajicDesigns/MD_AD9833

I'm not that good at code to find the difference ,,, But there is surly one somewere !

**Comment by RobTillaart** [comment] 2023-12-15 18:39
Interesting, I will check when time permit

**Comment by T1j3ff** [comment] 2023-12-15 23:33
Sniffing a bit the SPI , I can see the other library seems to send 3 chunk of data to change freq, but your send 2. My scope isn't good enough to decode data though.
I'll keep my circuit near , if ever you need to try more

**Comment by RobTillaart** [comment] 2023-12-16 04:39
Good morning
That library updates the control register explicitly at every update of the frequency. I had seen that too, but I still have to do some test runs and compare the bytes send. 
To be continued

**Comment by RobTillaart** [comment] 2023-12-16 08:51
Adapted my library to always send the control byte too.
Now try to find some hardware...

----

update: added print statements in both libraries and set the frequency to 1000 Hz.
Both send the same bytes over SPI, so math and control byte are identical (now).

The MD library however does send several bytes for initialization. so that is a point of attention.

----

log from the initialization of the MD library - need to set a flag AD_DEBUG 1 in **MD_AD9833_lib.h**
(nice feature)

``` 
Hardware SPI
spiSend 0x2000 CTL  B28 --- --- --- --- --- --- --- --- ---
spiSend 0x2100 CTL  B28 --- --- --- RST --- --- --- --- ---
setFreq CHAN_0 - freq 1000.00 = 0x29F1
spiSend 0x2100 CTL  B28 --- --- --- RST --- --- --- --- ---
spiSend 0x69F1 FQ0 0x29F1
spiSend 0x4000 FQ0 0x0
setFreq CHAN_1 - freq 1000.00 = 0x29F1
spiSend 0x2100 CTL  B28 --- --- --- RST --- --- --- --- ---
spiSend 0xA9F1 FQ1 0x29F1
spiSend 0x8000 FQ1 0x0
setPhase CHAN_0 - phase 0 = 0x0
spiSend 0xC000 PH0 0x0
setPhase CHAN_1 - phase 0 = 0x0
spiSend 0xE000 PH1 0x0
spiSend 0x2100 CTL  B28 --- --- --- RST --- --- --- --- ---
spiSend 0x2000 CTL  B28 --- --- --- --- --- --- --- --- ---
setWave SINE
spiSend 0x2000 CTL  B28 --- --- --- --- --- --- --- --- ---
setActiveFreq CHAN_0
spiSend 0x2000 CTL  B28 --- --- --- --- --- --- --- --- ---
setActivePhase CHAN_0
spiSend 0x2000 CTL  B28 --- --- --- --- --- --- --- --- ---


setFreq CHAN_0 - freq 1000.00 = 0x29F1
spiSend 0x2000 CTL  B28 --- --- --- --- --- --- --- --- ---
spiSend 0x69F1 FQ0 0x29F1
spiSend 0x4000 FQ0 0x0
```

It explicitly sets all defaults after reset of the device.
I expect that should not make a difference, as datasheet does not mentions it is needed.

The main difference so far is that MD is sending the control byte explicitly. 

Changed that in my library too, so please give the latest version a try.

**Comment by RobTillaart** [comment] 2023-12-16 11:00
Found some hardware, confirmed that the glitch is there  ==> bug 
and the glitch is gone when the control register is written explicitly.
(do not understand why, but OK).

Tested with sine and square 

----

Also tested the new HLB mode calls, which write directly into the LSB or MSB frequency register.
These allow a finer control of the frequency than **setFrequency()** 

Also added updated performance figures .

**Closed as completed** 2023-12-18 10:21 UTC
Labels: bug, question

**Comment by RobTillaart** [comment] 2023-12-18 10:32
Merged the fix into master.
If needed you can reopen the issue.
